networks:
  pihole-net:
    external: true

services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    env_file:
      - .env
    volumes:
      - "./data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "DIUN_WATCH_WORKERS=20"
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - "DIUN_WATCH_JITTER=30s"
      - "DIUN_PROVIDERS_DOCKER=true"
      - "DIUN_NOTIF_NTFY_ENDPOINT=http://ntfy:80"
      - "DIUN_NOTIF_NTFY_TOPIC=diun"
      - "DIUN_NOTIF_NTFY_PRIORITY=3"
      - "DIUN_NOTIF_NTFY_TAGS=package"
    restart: unless-stopped

    networks:
      - pihole-net
    labels:
      - "com.docker.compose.project=diun"
      - "com.docker.compose.service=diun"
      - "diun.enable=true"
