networks:
  pihole-net:
    external: true

services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:v1.53.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr/appdata:/appdata
    networks:
      - pihole-net
    environment:
      - SECRET_ENCRYPTION_KEY=${SECRET_ENCRYPTION_KEY}
    ports:
      - '7575:7575'
    labels:
      - "com.docker.compose.project=homarr"
      - "com.docker.compose.service=homarr"
