networks:
  pihole-net:
    external: true

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_MONITOR_ONLY: "true"
      WATCHTOWER_CLEANUP: "false"
      WATCHTOWER_POLL_INTERVAL: "86400"
    restart: unless-stopped

    networks:
      - pihole-net
    labels:
      - "com.docker.compose.project=watchtower"
      - "com.docker.compose.service=watchtower"
